---
- name: Deploy and configure PostgreSQL
  hosts: db
  become: yes
  roles:
    - role: postgresql
      vars:
        postgresql_databases:
          - name: app_db
            encoding: UTF-8
            lc_collate: en_US.UTF-8
            lc_ctype: en_US.UTF-8
          - name: test_db
            encoding: UTF-8
            lc_collate: C
            lc_ctype: C
